### ISSUE TITLE
Bug on spawning traders

### ISSUE THREAD

**Issue by jottyfan** [jottyfan/JottysMod#4]
#3 -- Head --
Stacktrace:
	at de.jotty.mymod.trader.Trader.getCanSpawnHere(Trader.java:61)
	at net.minecraft.world.WorldEntitySpawner.findChunksForSpawning(WorldEntitySpawner.java:154)
	at net.minecraft.world.WorldServer.tick(WorldServer.java:202)
Stacktrace:
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:768)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:683)
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:155)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:532)
	at java.lang.Thread.run(Thread.java:745)

**Comment by jottyfan** [comment]
solved

**Comment by jottyfan** [comment]
java.lang.NullPointerException: Exception ticking world
	at de.jotty.mymod.trader.Trader.func_70601_bi(Trader.java:60)
hub.com/

**Comment by jottyfan** [comment]
solved really
